services:
  postgres:
    image: postgres:latest
    container_name: sample-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sample
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/resources/init.sql
      - ./postgres-data:/var/lib/postgresql/data