server:
  address: 0.0.0.0
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sample-project

  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
#    url: jdbc:postgresql://43.200.244.12:5432/sample
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: password

  jpa:
    hibernate:
      ddl-auto: none  # Hibernate가 테이블 생성 안 하도록 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql  # 테이블 생성 쿼리
      data-locations: classpath:data.sql      # 초기 데이터 삽입

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

jwt:
#  secret: ${JWT_SECRET}
  secret: 5OORB6y28xXu4WXSRyMUh_S8hMXVZtqrqvKxqNZeHxeX_iKZjJZ1dXOsCjp30M7EDAg0-1RAE331cg-b8GomvQ==
  expiration: 900000
#  refresh-secret: ${JWT_REFRESH_SECRET}
  refresh-secret: OqYwklzc6LqeSKMi5viZ6SN2CPxn-QYt0jP5JXQC_OeqMIpc-4tPAVdp2Ee4V6o6OWbJFigAXRv_huCW-_OYqQ==
  refresh-expiration: 604800000

logging:
  level:
    com.profect.delivery.global.security: DEBUG
    org.springframework.security: DEBUG