server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: sample-project

  datasource:
#    url: jdbc:postgresql://localhost:5432/sample
#    driver-class-name: org.postgresql.Driver
#    username: user
#    password: password
    url: jdbc:postgresql://43.200.244.12:5432/sample
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none  # Hibernate가 테이블 생성 안 하도록 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql  # 테이블 생성 쿼리
      data-locations: classpath:data.sql      # 초기 데이터 삽입

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25UaGF0SXNMb25nRW5vdWdoQW5kUmFuZG9t
  expiration: 86400000  # 24 hours in milliseconds (1000 * 60 * 60 * 24)

logging:
  level:
    com.profect.delivery.global.security: DEBUG
    org.springframework.security: DEBUG